# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        self.menuLoad = QtWidgets.QMenu(self.menubar)
        self.menuLoad.setObjectName("menuLoad")
        self.menuDefault_Graphs = QtWidgets.QMenu(self.menuLoad)
        self.menuDefault_Graphs.setObjectName("menuDefault_Graphs")
        self.menuSearch_Algorithms = QtWidgets.QMenu(self.menubar)
        self.menuSearch_Algorithms.setObjectName("menuSearch_Algorithms")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLocal_File = QtWidgets.QAction(MainWindow)
        self.actionLocal_File.setObjectName("actionLocal_File")
        self.actionaa = QtWidgets.QAction(MainWindow)
        self.actionaa.setObjectName("actionaa")
        self.actionBFS = QtWidgets.QAction(MainWindow)
        self.actionBFS.setObjectName("actionBFS")
        self.actionDFS = QtWidgets.QAction(MainWindow)
        self.actionDFS.setObjectName("actionDFS")
        self.actionUCS = QtWidgets.QAction(MainWindow)
        self.actionUCS.setObjectName("actionUCS")
        self.actionGreedy_Best_First = QtWidgets.QAction(MainWindow)
        self.actionGreedy_Best_First.setObjectName("actionGreedy_Best_First")
        self.actionA = QtWidgets.QAction(MainWindow)
        self.actionA.setObjectName("actionA")
        self.actionDijkstra = QtWidgets.QAction(MainWindow)
        self.actionDijkstra.setObjectName("actionDijkstra")
        self.actionBellman_Ford = QtWidgets.QAction(MainWindow)
        self.actionBellman_Ford.setObjectName("actionBellman_Ford")
        self.actionFloyd_Warshall = QtWidgets.QAction(MainWindow)
        self.actionFloyd_Warshall.setObjectName("actionFloyd_Warshall")
        self.actionPrim = QtWidgets.QAction(MainWindow)
        self.actionPrim.setObjectName("actionPrim")
        self.actionKruskal = QtWidgets.QAction(MainWindow)
        self.actionKruskal.setObjectName("actionKruskal")
        self.menuLoad.addAction(self.menuDefault_Graphs.menuAction())
        self.menuLoad.addAction(self.actionLocal_File)
        self.menuSearch_Algorithms.addAction(self.actionBFS)
        self.menuSearch_Algorithms.addAction(self.actionDFS)
        self.menuSearch_Algorithms.addAction(self.actionUCS)
        self.menuSearch_Algorithms.addSeparator()
        self.menuSearch_Algorithms.addAction(self.actionGreedy_Best_First)
        self.menuSearch_Algorithms.addAction(self.actionA)
        self.menuSearch_Algorithms.addSeparator()
        self.menuSearch_Algorithms.addAction(self.actionDijkstra)
        self.menuSearch_Algorithms.addAction(self.actionBellman_Ford)
        self.menuSearch_Algorithms.addAction(self.actionFloyd_Warshall)
        self.menuSearch_Algorithms.addSeparator()
        self.menuSearch_Algorithms.addAction(self.actionPrim)
        self.menuSearch_Algorithms.addAction(self.actionKruskal)
        self.menubar.addAction(self.menuLoad.menuAction())
        self.menubar.addAction(self.menuSearch_Algorithms.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Please Select a graph first"))
        self.menuLoad.setTitle(_translate("MainWindow", "Load"))
        self.menuDefault_Graphs.setTitle(_translate("MainWindow", "Default Graphs"))
        self.menuSearch_Algorithms.setTitle(_translate("MainWindow", "Search Algorithms"))
        self.actionLocal_File.setText(_translate("MainWindow", "Local File"))
        self.actionaa.setText(_translate("MainWindow", "aa"))
        self.actionBFS.setText(_translate("MainWindow", "BFS"))
        self.actionDFS.setText(_translate("MainWindow", "DFS"))
        self.actionUCS.setText(_translate("MainWindow", "UCS"))
        self.actionGreedy_Best_First.setText(_translate("MainWindow", "Greedy Best-First"))
        self.actionA.setText(_translate("MainWindow", "A*"))
        self.actionDijkstra.setText(_translate("MainWindow", "Dijkstra"))
        self.actionBellman_Ford.setText(_translate("MainWindow", "Bellman-Ford"))
        self.actionFloyd_Warshall.setText(_translate("MainWindow", "Floyd-Warshall"))
        self.actionPrim.setText(_translate("MainWindow", "Prim"))
        self.actionKruskal.setText(_translate("MainWindow", "Kruskal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
